src/BoostUp/Models/Companies/CompaniesQueryModel.cs
namespace BoostUp.Models.Companies
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using Common;
    using BoostUp.Services.Companies.Models;

    public class CompaniesQueryModel
    {
        public const int companiesPerPage = 8;

        public int CurrentPage { get; init; } = 1;

        public int TotalCompanies { get; set; }

        [Display(Name = "Filter by industry")]
        public int IndustryId { get; init; }

        public IEnumerable<CompanyIndustryServiceModel> Industries { get; set; }

        [Display(Name = "Search by name or year of establishment")]
        public string SearchTerm { get; init; }

        [Display(Name = "Filter by country")]
        public string Country { get; init; }

        public IEnumerable<string> Countries { get; set; }

        public CompanySorting Sorting { get; init; }

        public IEnumerable<CompanyServiceModel> Companies { get; set; }
    }
}

src/BoostUp/Models/Companies/CompanyBecomeEmployeeViewModel.cs
namespace BoostUp.Models.Companies
{
    public class CompanyBecomeEmployeeViewModel
    {
        public int CompanyId { get; init; }

        public string CompanyName { get; init; }

        public string UserFirstName { get; init; }
    }
}

src/BoostUp/Areas/Admin/Controllers/CompaniesController.cs
namespace BoostUp.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using BoostUp.Services.Companies;

    public class CompaniesController : AdminController
    {
        private readonly ICompanyService companies;

        public CompaniesController(ICompanyService companies) 
            => this.companies = companies;

        public IActionResult All()
        {
            var companies = this.companies
                .All(publicOnly: false)
                .Companies;

            return View(companies);
        }

        public IActionResult Approve(int id)
        {
            this.companies.Approve(id);

            return RedirectToAction(nameof(All));
        }
    }
}

src/BoostUp/Controllers/CompaniesController.cs
namespace BoostUp.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using BoostUp.Services.Users;
    using BoostUp.Models.Companies;
    using BoostUp.Services.Companies;
    using BoostUp.Infrastructure.Extensions;

    using static WebConstants;

    public class CompaniesController : Controller
    {
        private readonly ICompanyService companies;
        private readonly IUserService users;
        private readonly IMapper mapper;

        public CompaniesController(ICompanyService companies, IUserService users, IMapper mapper)
        {
            this.companies = companies;
            this.users = users;
            this.mapper = mapper;
        }

        [Authorize]
        public IActionResult Add()
        {
            return View(new CompanyInputModel
            {
                Categories = this.companies.AllCategories(),
                Industries = this.companies.AllIndustries()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(CompanyInputModel company)
        {
            if (!this.companies.CategoryExists(company.CategoryId))
            {
                this.ModelState.AddModelError(nameof(company.CategoryId), "Category does not exist.");
            }
            else if (!this.companies.IndustryExists(company.IndustryId))
            {
                this.ModelState.AddModelError(nameof(company.IndustryId), "Industry does not exist.");
            }

            if (!ModelState.IsValid)
            {
                company.Categories = this.companies.AllCategories();
                company.Industries = this.companies.AllIndustries();

                return View(company);
            }

            int companyId = this.companies.Create(
                company.Name,
                company.Founded,
                company.Overview,
                company.IndustryId,
                company.CategoryId,
                company.Address.Country,
                company.Address.City,
                company.Address.AddressText,
                company.LogoUrl,
                company.WebsiteUrl);

            TempData[GlobalMessageKey] = "Your company was added successfully and is awaiting for approval by the administrator!";

            return RedirectToAction(nameof(All));
        }

        public IActionResult All([FromQuery] CompaniesQueryModel query)
        {
            var companiesQuery = this.companies.All(
                query.Country,
                query.IndustryId,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                CompaniesQueryModel.companiesPerPage);

            var companyCountries = this.companies.AllCountries();
            var companyIndustries = this.companies.AllIndustries();

            query.TotalCompanies = companiesQuery.TotalCompanies;
            query.Companies = companiesQuery.Companies;
            query.Industries = companyIndustries;
            query.Countries = companyCountries;

            return View(query);
        }

        [Authorize]
        public IActionResult Details(int id, string information)
        {
            var company = this.companies.Details(id);

            if (company == null)
            {
                TempData[GlobalMessageKey] = "Oops... The company does not exist!";

                return RedirectToAction(nameof(All));
            }

            if (company.CompanyInformation() != information)
            {
                TempData[GlobalMessageKey] = "Oops... The company can be accessed only by correct id and details provided!";

                return RedirectToAction(nameof(All));
            }

            var userId = this.User.GetId();

            company.UserFirstName = this.users.FirstNameById(userId);
            company.UserIsEmployed = this.users.IsEmployed(userId);

            return View(company);
        }

        [Authorize]
        public IActionResult BecomeEmployee(CompanyBecomeEmployeeViewModel becomeEmployee) 
            => View(becomeEmployee);

        [HttpPost]
        [Authorize]
        public IActionResult BecomeEmployee(int id)
        {
            var userId = this.User.GetId();

            var result = this.companies.BecomeEmployee(userId, id);

            if (!result)
            {
                return BadRequest();
            }

            TempData[GlobalMessageKey] = "Your workplace was changed successfully!";

            var information = this.companies.InformationById(id);

            return RedirectToAction(nameof(Details), new { id, information });
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            if (!this.User.IsAdmin())
            {
                return Unauthorized();
            }

            var company = this.companies.Details(id);

            var companyInput = this.mapper.Map<CompanyInputModel>(company);

            companyInput.Industries = this.companies.AllIndustries();
            companyInput.Categories = this.companies.AllCategories();

            return View(companyInput);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, CompanyInputModel company)
        {
            var userIsAdmin = this.User.IsAdmin();

            if (!userIsAdmin)
            {
                return Unauthorized();
            }

            if (!this.companies.CategoryExists(company.CategoryId))
            {
                this.ModelState.AddModelError(nameof(company.CategoryId), "Category does not exist.");
            }

            if (!this.companies.IndustryExists(company.IndustryId))
            {
                this.ModelState.AddModelError(nameof(company.IndustryId), "Industry does not exist.");
            }

            if (!ModelState.IsValid)
            {
                company.Industries = this.companies.AllIndustries();
                company.Categories = this.companies.AllCategories();

                return View(company);
            }

            this.companies.Edit(
                id,
                company.Name,
                company.Founded,
                company.Overview,
                company.IndustryId,
                company.CategoryId,
                company.Address.Country,
                company.Address.City,
                company.Address.AddressText,
                company.LogoUrl,
                company.WebsiteUrl,
                userIsAdmin);

            TempData[GlobalMessageKey] = "The company was edited successfully!";

            var information = company.CompanyInformation();

            return RedirectToAction(nameof(Details), new { id, information });
        }
    }
}

src/BoostUp/Controllers/JobsController.cs
namespace BoostUp.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using BoostUp.Models.Jobs;
    using BoostUp.Services.Jobs;
    using BoostUp.Services.Users;
    using BoostUp.Services.Recruiters;
    using BoostUp.Infrastructure.Extensions;

    using static WebConstants;

    public class JobsController : Controller
    {
        private readonly IJobService jobs;
        private readonly IRecruiterService recruiters;
        private readonly IUserService users;
        private readonly IMapper mapper;

        public JobsController(IJobService jobs, IRecruiterService recruiters, IUserService users, IMapper mapper)
        {
            this.jobs = jobs;
            this.users = users;
            this.recruiters = recruiters;
            this.mapper = mapper;
        }

        [Authorize]
        public IActionResult Add(int companyId)
        {
            if (!this.recruiters.IsRecruiter(this.User.GetId()))
            {
                return RedirectToAction(nameof(RecruitersController.Become), "Recruiters", new { companyId });
            }

            return View(new JobInputModel
            {
                EmploymentTypes = this.jobs.AllEmploymentTypes()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(JobInputModel job)
        {
            var recruiterId = this.recruiters.IdByUser(this.User.GetId());

            if (recruiterId == null)
            {
                return RedirectToAction(nameof(RecruitersController.Become), "Recruiters", new { value = "companyId" });
            }

            if (!this.jobs.EmploymentTypeExists(job.EmploymentTypeId))
            {
                this.ModelState.AddModelError(nameof(job.EmploymentTypeId), "Employment type does not exist.");
            }

            if (!ModelState.IsValid)
            {
                job.EmploymentTypes = this.jobs.AllEmploymentTypes();

                return View(job);
            }

            int id = this.jobs.Create(
                job.JobTitle,
                job.Address.Country,
                job.Address.City,
                job.Address.AddressText,
                job.Description,
                recruiterId,
                job.EmploymentTypeId,
                job.SalaryRangeFrom,
                job.SalaryRangeTo,
                job.CompanyId);

            TempData[GlobalMessageKey] = "You have add the job successfully!";

            var information = this.jobs.InformationById(id);

            return RedirectToAction(nameof(Details), new { id, information });
        }

        public IActionResult All([FromQuery] JobsQueryModel query)
        {
            var jobsQuery = this.jobs.All(
                query.CompanyId,
                query.Country,
                query.EmploymentTypeId,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                JobsQueryModel.jobsPerPage);

            var jobCountries = this.jobs.AllCountries();
            var jobEmploymentTypes = this.jobs.AllEmploymentTypes();

            query.Jobs = jobsQuery.Jobs;
            query.TotalJobs = jobsQuery.TotalJobs;
            query.Countries = jobCountries;
            query.EmploymentTypes = jobEmploymentTypes;

            return View(query);
        }

        [Authorize]
        public IActionResult Mine()
        {
            if (!this.recruiters.IsRecruiter(this.User.GetId()))
            {
                return BadRequest();
            }

            var userId = this.User.GetId();

            var myJobs = this.jobs.ByUser(userId);

            return View(myJobs);
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = this.User.GetId();

            if (!this.recruiters.IsRecruiter(userId) && !this.User.IsAdmin())
            {
                return RedirectToAction(nameof(RecruitersController.Become), "Recruiters", new { companyId = 0 });
            }

            var job = this.jobs.Details(id);

            if (job.UserId != userId && !this.User.IsAdmin())
            {
                return Unauthorized();
            }

            var jobInput = this.mapper.Map<JobInputModel>(job);

            jobInput.EmploymentTypes = this.jobs.AllEmploymentTypes();

            return View(jobInput);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, JobInputModel job)
        {
            var recruiterId = this.recruiters.IdByUser(this.User.GetId());

            if (recruiterId == null && !this.User.IsAdmin())
            {
                return RedirectToAction(nameof(RecruitersController.Become), "Recruiters", new { value = "companyId" });
            }

            if (!this.jobs.EmploymentTypeExists(job.EmploymentTypeId))
            {
                this.ModelState.AddModelError(nameof(job.EmploymentTypeId), "Employment type does not exist.");
            }

            if (!ModelState.IsValid)
            {
                job.EmploymentTypes = this.jobs.AllEmploymentTypes();

                return View(job);
            }

            if (!this.jobs.IsByRecruiter(id, recruiterId) && !this.User.IsAdmin())
            {
                return BadRequest();
            }

            this.jobs.Edit(
                  id,
                  job.JobTitle,
                  job.Address.Country,
                  job.Address.City,
                  job.Address.AddressText,
                  job.Description,
                  job.EmploymentTypeId,
                  job.SalaryRangeFrom,
                  job.SalaryRangeTo,
                  job.CompanyId);

            TempData[GlobalMessageKey] = $"{(this.User.IsAdmin() ? "The" : "Your")} job was edited successfully.";

            var information = this.jobs.InformationById(id);

            return RedirectToAction(nameof(Details), new { id, information });
        }

        [Authorize]
        public IActionResult Details(int id, string information)
        {
            var job = this.jobs.Details(id);

            if (job == null)
            {
                TempData[GlobalMessageKey] = "Oops... The job does not exist!";

                return RedirectToAction(nameof(All));
            }

            if (job.JobInformation() != information)
            {
                TempData[GlobalMessageKey] = "Oops... The job can be accessed only by correct id and details provided!";

                return RedirectToAction(nameof(All));
            }

            job.Views = this.jobs.JobViews(id);
            job.RecruiterFullName = this.users.FirstNameById(job.UserId) + " " + this.users.LastNameById(job.UserId);

            return View(job);
        }
    }
}

src/BoostUp/Controllers/UsersController.cs
namespace BoostUp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using BoostUp.Models.Users;
    using BoostUp.Services.Users;
    using BoostUp.Services.Friendships;
    using BoostUp.Infrastructure.Extensions;

    public class UsersController : Controller
    {
        private readonly IUserService users;
        private readonly IFriendshipService friendships;

        public UsersController(IUserService users, IFriendshipService friendships)
        {
            this.users = users;
            this.friendships = friendships;
        }

        [Authorize]
        public IActionResult Profile(string id)
        {
            var user = this.users.Details(id);

            if (user == null)
            {
                return Unauthorized();
            }

            user.CurrentLoggedUser = User.GetId();

            user.FriendShip = this.friendships.GetFriendship(user.CurrentLoggedUser, id);

            return View(user);
        }

        [Authorize]
        public IActionResult All([FromQuery] UsersQueryModel query)
        {
            var userId = User.GetId();

            var usersQuery = this.users.All(
                query.SearchTerm,
                query.CurrentPage,
                UsersQueryModel.usersPerPage,
                query.CompanyId,
                userId);    

            query.Users = usersQuery.Users;
            query.TotalUsers = usersQuery.TotalUsers;

            return View(query);
        }
    }
}

src/BoostUp/Views/Companies/Add.cshtml
@model CompanyInputModel

@{
    ViewBag.Title = "Register Company";
}

<partial name="_CompanyInputPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/BoostUp/Views/Companies/All.cshtml
@model CompaniesQueryModel

@{
    ViewBag.Title = "Companies";
}

<!-- Filter, Sort and Search -->
<form method="get">
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="Country"></label>
            <select asp-for="Country" class="form-control shadow">
                <option value="">&#10150; All</option>
                @foreach (var country in Model.Countries)
                {
                    <option value="@country">&#9992; @country</option>
                }
            </select>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="IndustryId"></label>
            <select asp-for="IndustryId" class="form-control shadow">
                <option value="">&#10150; All</option>
                @foreach (var industry in Model.Industries)
                {
                    <option value="@industry.Id">&#9874; @industry.Value</option>
                }
            </select>
        </div>
        <div class="form-group col-md-4">
            <div class="form-group">
                <label asp-for="Sorting"></label>
                <select asp-for="Sorting" class="form-control shadow">
                    <option value="0" selected>&bull; Date created</option>
                    <option value="1">&bull; Year of establishment</option>
                    <option value="2">&bull; Company name</option>
                    <option value="3">&bull; Employees count</option>
                </select>
            </div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="form-group offset-4 col-4">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control shadow" type="text" placeholder="Search" aria-label="Search">
        </div>
    </div>
    <div class="d-flex justify-content-center mb-4">
        <button class="btn btn-outline-primary btn-rounded btn-md shadow" type="submit">Search</button>
    </div>
</form>

<hr />

<!-- Body -->
@if (!Model.Companies.Any())
{
    <h2 class="text-center mt-4"> &#x1F62D;</h2>
    <h3 class="text-center mb-5">No companies found!</h3>
}
else
{
    <!-- Pagination -->
    <partial name="_CompaniesPaginationPartial" model="@Model" />

    <div class="row">
        @foreach (var company in Model.Companies)
        {
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="card bg-light mb-4 shadow" style="max-width: 18rem;">
                    <div class="card-header">
                        <div>
                            <a asp-action="Details" asp-controller="Companies" asp-route-id="@company.Id" asp-route-information="@company.CompanyInformation()">
                                @if (company.LogoUrl != null)
                                {
                                    <img class="card-img-top rounded-circle mb-2 img-thumbnail shadow" src="@company.LogoUrl" alt="@company.Name - Logo">
                                }
                                else
                                {
                                    <img class="card-img-top rounded-circle mb-2 img-thumbnail shadow" src="~/default pictures/Company Logo.jpg" alt="@company.Name - Logo">
                                }
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center mb-2"><b>@company.Name</b></h5>
                        <p class="card-text text-center mb-3"><i>@company.CategoryName</i></p>
                        <p class="card-text mb-2"><b>Industry:</b> @company.IndustryName</p>
                        <p class="card-text mb-2"><b>Location:</b> @company.City, @company.Country</p>
                        <p class="card-text mb-2"><b>Founded:</b> @company.Founded</p>
                        <a asp-action="Details"
                           asp-controller="Companies"
                           asp-route-id="@company.Id"
                           asp-route-information="@company.CompanyInformation()" class="btn btn-outline-primary shadow">
                            Details
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>

    <!-- Pagination -->
    <partial name="_CompaniesPaginationPartial" model="@Model" />
}

<hr />

src/BoostUp/Views/Companies/BecomeEmployee.cshtml
@model CompanyBecomeEmployeeViewModel

@{
    ViewBag.Title = "Become Employee";
}

<form method="post">
    <div class="text-center mt-4 mb-4">
        <h2>Are you sure you want to change your work place to @Model.CompanyName?</h2>
        <div class="d-flex justify-content-center mb-4">
            <button class="btn btn-outline-primary btn-rounded btn-md shadow" type="submit">Change company</button>
        </div>
    </div>
</form>

src/BoostUp/Views/Companies/Details.cshtml
@model CompanyDetailsServiceModel

@{
    ViewBag.Title = $"{Model.Name}: Details";
}

<div class="offset-lg-1 col-lg-10">
    <div class="bg-white shadow rounded overflow-hidden">
        <div class="card-header">
            <div class="row">
                <div class="col-3">
                    <div class="card bg-light mb-2 shadow" style="max-width: 14rem;">
                        <div class="card-header">
                            @if (Model.LogoUrl != null)
                            {
                                <img class="card-img-top rounded-circle mb-2 img-thumbnail" src="@Model.LogoUrl" alt="@Model.Name - Logo">
                            }
                            else
                            {
                                <img class="card-img-top rounded-circle mb-2 img-thumbnail" src="~/default pictures/Company Logo.jpg" alt="@Model.Name - Logo">
                            }
                        </div>
                        <h5 class="card-title text-center mb-2"><b>@Model.Name</b></h5>
                        <h6 class="text-muted text-center">@Model.IndustryName</h6>
                    </div>
                </div>
                <div class="col-4">
                    <div class="row">
                        @if (!User.IsAdmin())
                        {
                            <a asp-controller="Jobs" asp-action="Add" asp-route-companyId="@Model.Id" class="btn btn-outline-warning m-2">
                                <b>Post a job</b>
                            </a>
                        }
                    </div>
                    <div class="row">
                        <a asp-controller="Jobs" asp-action="All" asp-route-companyId="@Model.Id" class="btn btn-outline-primary m-2">
                            <b>@Model.JobsCount @(Model.JobsCount == 1 ? "Job" : "Jobs")</b>
                        </a>
                    </div>
                    <div class="row">
                        <a asp-controller="Users" asp-action="All" asp-route-companyId="@Model.Id" class="btn btn-outline-primary m-2">
                            <b>@Model.EmployeesCount @(Model.EmployeesCount == 1 ? "Employee" : "Employees")</b>
                        </a>
                    </div>
                </div>
            </div>
            @if (!User.IsAdmin() && !Model.UserIsEmployed)
            {
                <div class="row mt-2">
                    <p class="text-primary"><b><i>&nbsp&nbsp @Model.UserFirstName, are you an employee of this company? &nbsp</i></b></p>
                    <p>
                        <a asp-controller="Companies"
                           asp-action="BecomeEmployee"
                           asp-route-id="@Model.Id"
                           asp-route-companyName="@Model.Name"
                           asp-route-userFirstName="@Model.UserFirstName" class="text-warning">
                            <b><i>Yes</i></b>
                        </a>
                    </p>
                </div>
            }
        </div>
        <div class="card-body">
            <div id="accordion">
                <div class="card mb-4">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                <h5><b>Overview</b></h5>
                            </button>
                        </h5>
                    </div>
                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="card-body">
                            @Model.Overview
                        </div>
                    </div>
                </div>
            </div>
            @if (Model.WebsiteUrl != null)
            {
                <p class="card-text mb-2"><b>Website:</b> <a href="@Model.WebsiteUrl">@Model.WebsiteUrl</a></p>
            }
            <p class="card-text mb-2"><b>Industry:</b> @Model.IndustryName</p>
            <p class="card-text mb-2"><b>Company size:</b> @Model.CategoryName &nbsp<i>/@Model.EmployeesCount on <b>BoostUp</b>/</i></p>
            <p class="card-text mb-2"><b>Location:</b> @Model.City, @Model.Country</p>
            @if (Model.AddressText != null)
            {
                <p class="card-text mb-2"><b>Address:</b> @Model.AddressText</p>
            }
            <p class="card-text mb-4"><b>Founded:</b> @Model.Founded</p>
        </div>
        <div class="card-footer text-muted">
            @if (User.IsAdmin())
            {
                <div class="text-center">
                    <a asp-action="Edit" asp-controller="Companies" asp-route-id="@Model.Id" class="btn btn-outline-warning shadow m-2">Edit</a>
                </div>
            }
        </div>
    </div>
</div>

src/BoostUp/Views/Companies/Edit.cshtml
@model CompanyInputModel

@{
    ViewBag.Title = "Edit company";
    ViewBag.EditPartial = true;
}

<div class="offset-sm-3 col-sm-6 offset-md-4 col-md-4 mt-5 mb-4"><h2 class="heading-margin text-center">@ViewBag.Title</h2></div>

<partial name="_CompanyInputPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/BoostUp/Views/Companies/_CompaniesPaginationPartial.cshtml
@model CompaniesQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    var currentPage = Model.CurrentPage;

    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var lastPage = (int)Math.Ceiling((double)Model.TotalCompanies / CompaniesQueryModel.companiesPerPage);
}

<nav>
    <ul class="pagination justify-content-center mb-4">
        <li class="page-item @(currentPage <= 1 ? "disabled" : String.Empty)">
            <a class="page-link"
               asp-controller="Companies" asp-action="All"
               asp-route-currentPage="@previousPage"
               asp-route-country="@Model.Country"
               asp-route-industryId="@Model.IndustryId"
               asp-route-searchTerm="@Model.SearchTerm"
               asp-route-sorting="@((int)Model.Sorting)">Previous</a>
        </li>
        @for (int i = currentPage - 3; i < currentPage; i++)
        {
            if (i > 0)
            {
                <li class="page-item">
                    <a class="page-link"
                       asp-controller="Companies" asp-action="All"
                       asp-route-currentPage="@i"
                       asp-route-country="@Model.Country"
                       asp-route-industryId="@Model.IndustryId"
                       asp-route-searchTerm="@Model.SearchTerm"
                       asp-route-sorting="@((int)Model.Sorting)">@i</a>
                </li>
            }
        }
        <li class="page-item active">
            <span class="page-link">
                @currentPage
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = currentPage + 1; i < currentPage + 4; i++)
        {
            if (i <= lastPage)
            {
                <li class="page-item">
                    <a class="page-link"
                       asp-controller="Companies" asp-action="All"
                       asp-route-currentPage="@i"
                       asp-route-country="@Model.Country"
                       asp-route-industryId="@Model.IndustryId"
                       asp-route-searchTerm="@Model.SearchTerm"
                       asp-route-sorting="@((int)Model.Sorting)">@i</a>
                </li>
            }
        }
        <li class="page-item @(currentPage >= lastPage ? "disabled" : String.Empty)">
            <a class="page-link"
               asp-controller="Companies" asp-action="All"
               asp-route-currentPage="@(currentPage + 1)"
               asp-route-country="@Model.Country"
               asp-route-industryId="@Model.IndustryId"
               asp-route-searchTerm="@Model.SearchTerm"
               asp-route-sorting="@((int)Model.Sorting)">Next</a>
        </li>
    </ul>
</nav>