src/BoostUp/Models/Jobs/JobInputModel.cs
namespace BoostUp.Models.Jobs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using BoostUp.Models.Addresses;
    using BoostUp.Services.Jobs.Models;
    using Microsoft.AspNetCore.Mvc.ModelBinding;

    using static BoostUp.Common.DataConstants.Job;

    public class JobInputModel : IJobModel
    {
        [Display(Name = "Job title")]
        [Required(ErrorMessage = "{0} is required.")]
        [StringLength(TitleMaxLength, MinimumLength = TitleMinLength, ErrorMessage = "{0} must be with a minimum length of {2} and a maximum length of {1}.")]
        public string JobTitle { get; init; }

        public AddressInputModel Address { get; init; }

        [Display(Name = "Salary range from:")]
        [Range(SalaryMinRange, SalaryMaxRange, ErrorMessage = SalaryRangeMessage)]
        public int? SalaryRangeFrom { get; init; }

        [Display(Name = "Salary range to:")]
        [Range(SalaryMinRange, SalaryMaxRange, ErrorMessage = SalaryRangeMessage)]
        public int? SalaryRangeTo { get; init; }

        [Required(ErrorMessage = "{0} is required.")]
        [MinLength(DescriptionMinLength, ErrorMessage = "{0} must be with a minimum length of {1}.")]
        public string Description { get; init; }

        public int CompanyId { get; init; }

        public int EmploymentTypeId { get; init; }

        [BindNever]
        public string EmploymentType { get; init; }

        [BindNever]
        public IEnumerable<JobEmploymentTypeServiceModel> EmploymentTypes { get; set; }
    }
}

src/BoostUp/Controllers/AppliesController.cs
namespace BoostUp.Controllers
{
    using BoostUp.Services.Jobs;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using static WebConstants;

    public class AppliesController : Controller
    {
        private readonly IJobService jobs;

        public AppliesController(IJobService jobs) 
            => this.jobs = jobs;

        [Authorize]
        public IActionResult Add(int jobId)
        {
            var information = this.jobs.InformationById(jobId);

            if (information == null)
            {
                return Unauthorized();
            }

            TempData[GlobalMessageKey] = $"You have applied to the job '{information}' successfully!";

            return RedirectToAction("Details", "Jobs", new { id = jobId, information });
        }
    }
}

src/BoostUp/Controllers/CompaniesController.cs
namespace BoostUp.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using BoostUp.Services.Users;
    using BoostUp.Models.Companies;
    using BoostUp.Services.Companies;
    using BoostUp.Infrastructure.Extensions;

    using static WebConstants;

    public class CompaniesController : Controller
    {
        private readonly ICompanyService companies;
        private readonly IUserService users;
        private readonly IMapper mapper;

        public CompaniesController(ICompanyService companies, IUserService users, IMapper mapper)
        {
            this.companies = companies;
            this.users = users;
            this.mapper = mapper;
        }

        [Authorize]
        public IActionResult Add()
        {
            return View(new CompanyInputModel
            {
                Categories = this.companies.AllCategories(),
                Industries = this.companies.AllIndustries()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(CompanyInputModel company)
        {
            if (!this.companies.CategoryExists(company.CategoryId))
            {
                this.ModelState.AddModelError(nameof(company.CategoryId), "Category does not exist.");
            }
            else if (!this.companies.IndustryExists(company.IndustryId))
            {
                this.ModelState.AddModelError(nameof(company.IndustryId), "Industry does not exist.");
            }

            if (!ModelState.IsValid)
            {
                company.Categories = this.companies.AllCategories();
                company.Industries = this.companies.AllIndustries();

                return View(company);
            }

            int companyId = this.companies.Create(
                company.Name,
                company.Founded,
                company.Overview,
                company.IndustryId,
                company.CategoryId,
                company.Address.Country,
                company.Address.City,
                company.Address.AddressText,
                company.LogoUrl,
                company.WebsiteUrl);

            TempData[GlobalMessageKey] = "Your company was added successfully and is awaiting for approval by the administrator!";

            return RedirectToAction(nameof(All));
        }

        public IActionResult All([FromQuery] CompaniesQueryModel query)
        {
            var companiesQuery = this.companies.All(
                query.Country,
                query.IndustryId,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                CompaniesQueryModel.companiesPerPage);

            var companyCountries = this.companies.AllCountries();
            var companyIndustries = this.companies.AllIndustries();

            query.TotalCompanies = companiesQuery.TotalCompanies;
            query.Companies = companiesQuery.Companies;
            query.Industries = companyIndustries;
            query.Countries = companyCountries;

            return View(query);
        }

        [Authorize]
        public IActionResult Details(int id, string information)
        {
            var company = this.companies.Details(id);

            if (company == null)
            {
                TempData[GlobalMessageKey] = "Oops... The company does not exist!";

                return RedirectToAction(nameof(All));
            }

            if (company.CompanyInformation() != information)
            {
                TempData[GlobalMessageKey] = "Oops... The company can be accessed only by correct id and details provided!";

                return RedirectToAction(nameof(All));
            }

            var userId = this.User.GetId();

            company.UserFirstName = this.users.FirstNameById(userId);
            company.UserIsEmployed = this.users.IsEmployed(userId);

            return View(company);
        }

        [Authorize]
        public IActionResult BecomeEmployee(CompanyBecomeEmployeeViewModel becomeEmployee) 
            => View(becomeEmployee);

        [HttpPost]
        [Authorize]
        public IActionResult BecomeEmployee(int id)
        {
            var userId = this.User.GetId();

            var result = this.companies.BecomeEmployee(userId, id);

            if (!result)
            {
                return BadRequest();
            }

            TempData[GlobalMessageKey] = "Your workplace was changed successfully!";

            var information = this.companies.InformationById(id);

            return RedirectToAction(nameof(Details), new { id, information });
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            if (!this.User.IsAdmin())
            {
                return Unauthorized();
            }

            var company = this.companies.Details(id);

            var companyInput = this.mapper.Map<CompanyInputModel>(company);

            companyInput.Industries = this.companies.AllIndustries();
            companyInput.Categories = this.companies.AllCategories();

            return View(companyInput);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, CompanyInputModel company)
        {
            var userIsAdmin = this.User.IsAdmin();

            if (!userIsAdmin)
            {
                return Unauthorized();
            }

            if (!this.companies.CategoryExists(company.CategoryId))
            {
                this.ModelState.AddModelError(nameof(company.CategoryId), "Category does not exist.");
            }

            if (!this.companies.IndustryExists(company.IndustryId))
            {
                this.ModelState.AddModelError(nameof(company.IndustryId), "Industry does not exist.");
            }

            if (!ModelState.IsValid)
            {
                company.Industries = this.companies.AllIndustries();
                company.Categories = this.companies.AllCategories();

                return View(company);
            }

            this.companies.Edit(
                id,
                company.Name,
                company.Founded,
                company.Overview,
                company.IndustryId,
                company.CategoryId,
                company.Address.Country,
                company.Address.City,
                company.Address.AddressText,
                company.LogoUrl,
                company.WebsiteUrl,
                userIsAdmin);

            TempData[GlobalMessageKey] = "The company was edited successfully!";

            var information = company.CompanyInformation();

            return RedirectToAction(nameof(Details), new { id, information });
        }
    }
}

src/BoostUp/Controllers/JobsController.cs
namespace BoostUp.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using BoostUp.Models.Jobs;
    using BoostUp.Services.Jobs;
    using BoostUp.Services.Users;
    using BoostUp.Services.Recruiters;
    using BoostUp.Infrastructure.Extensions;

    using static WebConstants;

    public class JobsController : Controller
    {
        private readonly IJobService jobs;
        private readonly IRecruiterService recruiters;
        private readonly IUserService users;
        private readonly IMapper mapper;

        public JobsController(IJobService jobs, IRecruiterService recruiters, IUserService users, IMapper mapper)
        {
            this.jobs = jobs;
            this.users = users;
            this.recruiters = recruiters;
            this.mapper = mapper;
        }

        [Authorize]
        public IActionResult Add(int companyId)
        {
            if (!this.recruiters.IsRecruiter(this.User.GetId()))
            {
                return RedirectToAction(nameof(RecruitersController.Become), "Recruiters", new { companyId });
            }

            return View(new JobInputModel
            {
                EmploymentTypes = this.jobs.AllEmploymentTypes()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(JobInputModel job)
        {
            var recruiterId = this.recruiters.IdByUser(this.User.GetId());

            if (recruiterId == null)
            {
                return RedirectToAction(nameof(RecruitersController.Become), "Recruiters", new { value = "companyId" });
            }

            if (!this.jobs.EmploymentTypeExists(job.EmploymentTypeId))
            {
                this.ModelState.AddModelError(nameof(job.EmploymentTypeId), "Employment type does not exist.");
            }

            if (!ModelState.IsValid)
            {
                job.EmploymentTypes = this.jobs.AllEmploymentTypes();

                return View(job);
            }

            int id = this.jobs.Create(
                job.JobTitle,
                job.Address.Country,
                job.Address.City,
                job.Address.AddressText,
                job.Description,
                recruiterId,
                job.EmploymentTypeId,
                job.SalaryRangeFrom,
                job.SalaryRangeTo,
                job.CompanyId);

            TempData[GlobalMessageKey] = "You have add the job successfully!";

            var information = this.jobs.InformationById(id);

            return RedirectToAction(nameof(Details), new { id, information });
        }

        public IActionResult All([FromQuery] JobsQueryModel query)
        {
            var jobsQuery = this.jobs.All(
                query.CompanyId,
                query.Country,
                query.EmploymentTypeId,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                JobsQueryModel.jobsPerPage);

            var jobCountries = this.jobs.AllCountries();
            var jobEmploymentTypes = this.jobs.AllEmploymentTypes();

            query.Jobs = jobsQuery.Jobs;
            query.TotalJobs = jobsQuery.TotalJobs;
            query.Countries = jobCountries;
            query.EmploymentTypes = jobEmploymentTypes;

            return View(query);
        }

        [Authorize]
        public IActionResult Mine()
        {
            if (!this.recruiters.IsRecruiter(this.User.GetId()))
            {
                return BadRequest();
            }

            var userId = this.User.GetId();

            var myJobs = this.jobs.ByUser(userId);

            return View(myJobs);
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = this.User.GetId();

            if (!this.recruiters.IsRecruiter(userId) && !this.User.IsAdmin())
            {
                return RedirectToAction(nameof(RecruitersController.Become), "Recruiters", new { companyId = 0 });
            }

            var job = this.jobs.Details(id);

            if (job.UserId != userId && !this.User.IsAdmin())
            {
                return Unauthorized();
            }

            var jobInput = this.mapper.Map<JobInputModel>(job);

            jobInput.EmploymentTypes = this.jobs.AllEmploymentTypes();

            return View(jobInput);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, JobInputModel job)
        {
            var recruiterId = this.recruiters.IdByUser(this.User.GetId());

            if (recruiterId == null && !this.User.IsAdmin())
            {
                return RedirectToAction(nameof(RecruitersController.Become), "Recruiters", new { value = "companyId" });
            }

            if (!this.jobs.EmploymentTypeExists(job.EmploymentTypeId))
            {
                this.ModelState.AddModelError(nameof(job.EmploymentTypeId), "Employment type does not exist.");
            }

            if (!ModelState.IsValid)
            {
                job.EmploymentTypes = this.jobs.AllEmploymentTypes();

                return View(job);
            }

            if (!this.jobs.IsByRecruiter(id, recruiterId) && !this.User.IsAdmin())
            {
                return BadRequest();
            }

            this.jobs.Edit(
                  id,
                  job.JobTitle,
                  job.Address.Country,
                  job.Address.City,
                  job.Address.AddressText,
                  job.Description,
                  job.EmploymentTypeId,
                  job.SalaryRangeFrom,
                  job.SalaryRangeTo,
                  job.CompanyId);

            TempData[GlobalMessageKey] = $"{(this.User.IsAdmin() ? "The" : "Your")} job was edited successfully.";

            var information = this.jobs.InformationById(id);

            return RedirectToAction(nameof(Details), new { id, information });
        }

        [Authorize]
        public IActionResult Details(int id, string information)
        {
            var job = this.jobs.Details(id);

            if (job == null)
            {
                TempData[GlobalMessageKey] = "Oops... The job does not exist!";

                return RedirectToAction(nameof(All));
            }

            if (job.JobInformation() != information)
            {
                TempData[GlobalMessageKey] = "Oops... The job can be accessed only by correct id and details provided!";

                return RedirectToAction(nameof(All));
            }

            job.Views = this.jobs.JobViews(id);
            job.RecruiterFullName = this.users.FirstNameById(job.UserId) + " " + this.users.LastNameById(job.UserId);

            return View(job);
        }
    }
}

src/BoostUp/Controllers/UsersController.cs
namespace BoostUp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using BoostUp.Models.Users;
    using BoostUp.Services.Users;
    using BoostUp.Services.Friendships;
    using BoostUp.Infrastructure.Extensions;

    public class UsersController : Controller
    {
        private readonly IUserService users;
        private readonly IFriendshipService friendships;

        public UsersController(IUserService users, IFriendshipService friendships)
        {
            this.users = users;
            this.friendships = friendships;
        }

        [Authorize]
        public IActionResult Profile(string id)
        {
            var user = this.users.Details(id);

            if (user == null)
            {
                return Unauthorized();
            }

            user.CurrentLoggedUser = User.GetId();

            user.FriendShip = this.friendships.GetFriendship(user.CurrentLoggedUser, id);

            return View(user);
        }

        [Authorize]
        public IActionResult All([FromQuery] UsersQueryModel query)
        {
            var userId = User.GetId();

            var usersQuery = this.users.All(
                query.SearchTerm,
                query.CurrentPage,
                UsersQueryModel.usersPerPage,
                query.CompanyId,
                userId);    

            query.Users = usersQuery.Users;
            query.TotalUsers = usersQuery.TotalUsers;

            return View(query);
        }
    }
}

src/BoostUp/Views/Jobs/Add.cshtml
@model JobInputModel

@{
    ViewBag.Title = "Post a job";
}

<div class="col-sm-12 offset-md-1 col-md-10">
    <div class="row offset-2 col-8 mt-2">
        <div class="col-sm-12 col-lg-6"><img class="rounded-circle d-block w-100 text-center shadow" src="~/default pictures/Add Job Picture 2.jpg" alt="Recruiter img" /></div>
        <h6 class="heading-margin-h6 text-center col-sm-12 col-lg-6 mt-5">Post your job on the best professional network and get matched with the most qualified candidates for your role</h6>
    </div>
    <div class="row offset-2 col-8 mb-4">
        <div class="col-sm-12 col-lg-6"><h4 class="heading-margin-h4 text-center mt-5"><b><i>BoostUp</i></b> your work environment</h4></div>
        <div class="col-sm-12 col-lg-6"><img class="rounded-circle d-block w-100 text-center shadow" src="~/default pictures/Add Job Picture 1.jpg" alt="Recruiter img" /></div>
    </div>
</div>

<partial name="_JobInputPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/BoostUp/Views/Jobs/All.cshtml
@model JobsQueryModel

@{
    ViewBag.Title = "Jobs";
}

<!-- Filter, Sort and Search -->
<form method="get">
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="Country"></label>
            <select asp-for="Country" class="form-control shadow">
                <option value="">&#10150; All</option>
                @foreach (var country in Model.Countries)
                {
                    <option value="@country">&#9992; @country</option>
                }
            </select>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="EmploymentTypeId"></label>
            <select asp-for="EmploymentTypeId" class="form-control shadow">
                <option value="">&#10150; All</option>
                @foreach (var employmentType in Model.EmploymentTypes)
                {
                    <option value="@employmentType.Id"> @employmentType.Value</option>
                }
            </select>
        </div>
        <div class="form-group col-md-4">
            <div class="form-group">
                <label asp-for="Sorting"></label>
                <select asp-for="Sorting" class="form-control shadow">
                    <option value="0" selected>&bull; Date created</option>
                    <option value="1">&bull; Salary</option>
                    <option value="2">&bull; Job title</option>
                </select>
            </div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="form-group offset-4 col-4">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control shadow" type="text" placeholder="Search" aria-label="Search">
        </div>
    </div>
    <div class="d-flex justify-content-center mb-4">
        <button class="btn btn-outline-primary btn-rounded btn-md shadow" asp-route-companyId="@Model.CompanyId" type="submit">Search</button>
    </div>
</form>

<hr />

<!-- Body -->
@if (!Model.Jobs.Any())
{
    <h2 class="text-center mt-4"> &#x1F62D;</h2>
    <h3 class="text-center mb-5">No jobs found!</h3>
}
else
{
    if (Model.CompanyId > 0 && Model.CurrentPage == 1)
    {
        <h3 class="text-center mt-3 mb-5">@Model.TotalJobs @(Model.TotalJobs == 1 ? "job" : "jobs") found for @Model.Jobs.Select(j => j.Company.Name).FirstOrDefault()</h3>
    }

    <!-- Pagination -->
    <partial name="_JobsPaginationPartial" model="@Model" />

    <!-- All jobs -->
    <partial name="_JobsPartial" model="@Model.Jobs" />

    <!-- Pagination -->
    <partial name="_JobsPaginationPartial" model="@Model" />
}

<hr />

src/BoostUp/Views/Jobs/Details.cshtml
@model JobDetailsServiceModel

@{
    ViewBag.Title = $"{Model.JobTitle} | {Model.Company.Name}";
}

<div class="offset-lg-2 col-lg-8">
    <div class="bg-white shadow rounded overflow-hidden">
        <div class="card-header">
            <div class="row">
                <div class="col-8">
                    <div class="mb-2">
                        @if (Model.Company.LogoUrl != null)
                        {
                            <img class="rounded-circle mb-2 img-thumbnail shadow" width="100" height="100" src="@Model.Company.LogoUrl" alt="@Model.Company.Name - Logo">
                        }
                        else
                        {
                            <img class="rounded-circle mb-2 img-thumbnail shadow" width="100" height="100" src="~/default pictures/Company Logo.jpg" alt="@Model.Company.Name - Logo">
                        }
                    </div>
                    <h4 class="card-title mt-1 mb-2"><b>@Model.JobTitle</b></h4>
                    <h6 class="text-dark">
                        <a asp-controller="Companies"
                           asp-action="Details"
                           asp-route-information="@Model.Company.CompanyInformation()"
                           asp-route-id="@Model.Company.Id">
                            @Model.Company.Name
                        </a> &bull; @Model.City, @Model.Country <b>|</b> <span class="text-info">@Model.RelativeTime</span> &bull; <span class="text-info">Views: @Model.Views</span>
                    </h6>
                    <h6 class="card-text mt-4 mb-3">&#x1F4BC; @Model.EmploymentType</h6>
                    <h6 class="card-text mb-3">&#x1F3E2; @Model.Company.Category &bull; @Model.Company.Industry</h6>
                    @if (Model.AddressText != null)
                    {
                        <h6 class="card-text mb-3">&#x1F5FA; @Model.AddressText </h6>
                    }
                    @if (Model.SalaryRangeFrom != null)
                    {
                        <p><img alt="salary icon" src="~/default pictures/salary.png" /> @Model.SalaryRangeFrom @(Model.SalaryRangeTo == null ? string.Empty : $" - {Model.SalaryRangeTo}")</p>
                    }
                    @if (!User.IsAdmin())
                    {
                        <a asp-controller="Applies" asp-action="Add" asp-route-jobId="@Model.Id" class="btn btn-outline-warning m-2">
                            <b>Apply</b>
                        </a>
                    }
                </div>
            </div>
        </div>
        <div class="card-body">
            <div id="accordion">
                <div class="card mb-4">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                <h5><b>Job description</b></h5>
                            </button>
                        </h5>
                    </div>
                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="card-body">
                            @Model.Description
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            <div class="text-center">
                <h5 class="card-text mt-2 mb-4"><b><u>Recruiter details</u></b></h5>
                <p class="card-text mb-2">&#x1F471; <b><a asp-controller="Users" asp-action="Profile" asp-route-id="@Model.UserId">@Model.RecruiterFullName</a></b></p>
                <p class="card-text mb-2">&#9993; <b><a href="#">@Model.RecruiterEmail</a></b></p>
                @if (Model.RecruiterPhoneNumber != null)
                {
                    <p class="card-text mb-2">&#x260E; <b>@Model.RecruiterPhoneNumber</b></p>
                }
            </div>
        </div>
    </div>
</div>

src/BoostUp/Views/Jobs/Edit.cshtml
@model JobInputModel

@{
    ViewBag.Title = "Edit job";
    ViewBag.AllowJobEdit = true;
}

<div class="offset-sm-3 col-sm-6 offset-md-4 col-md-4 mt-5 mb-4"><h2 class="heading-margin text-center">@ViewBag.Title</h2></div>

<partial name="_JobInputPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/BoostUp/Views/Jobs/Mine.cshtml
@model IEnumerable<JobServiceModel>

@{
    ViewBag.Title = "My jobs";
    ViewBag.AllowJobEdit = true;
}

@if (!Model.Any())
{
    <h3 class="text-center mt-5">You do not have any jobs posted yet!</h3>
    <h2 class="text-center mb-5"> &#x1F62D;</h2>
}
else
{
    <div class="offset-sm-3 col-sm-6 offset-md-4 col-md-4 mt-4 mb-5"><h2 class="heading-margin text-center">@ViewBag.Title</h2></div>
}

<partial name="_JobsPartial" model="@Model" />

src/BoostUp/Views/Jobs/_JobInputPartial.cshtml
@model JobInputModel

<div class="container">
    <div class="row">
        <div class="offset-sm-1 col-sm-10 offset-md-2 col-md-8 offset-lg-3 col-lg-6">
            <form method="post">
                <div class="form-group">
                    <label asp-for="JobTitle" class="required"></label>
                    <input asp-for="JobTitle" class="form-control shadow">
                    <span asp-validation-for="JobTitle" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EmploymentTypeId" class="required">Employment type</label>
                    <select asp-for="EmploymentTypeId" class="form-control shadow">
                        @foreach (var EmploymentType in Model.EmploymentTypes)
                        {
                            <option value="@EmploymentType.Id">&bull; @EmploymentType.Value</option>
                        }
                    </select>
                    <span asp-validation-for="EmploymentTypeId" class="small text-danger"></span>
                </div>
                <div class="form-row">
                    <div class="form-group col-6">
                        <label asp-for="Address.Country" class="required"></label>
                        <input asp-for="Address.Country" class="form-control shadow" placeholder="England, USA...">
                        <span asp-validation-for="Address.Country" class="small text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="Address.City" class="required"></label>
                        <input asp-for="Address.City" class="form-control shadow" placeholder="London, New York...">
                        <span asp-validation-for="Address.City" class="small text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Address.AddressText"></label>
                    <input asp-for="Address.AddressText" class="form-control shadow" placeholder="Street, apartment, studio, or floor...">
                    <span asp-validation-for="Address.AddressText" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SalaryRangeFrom"></label>
                    <input asp-for="SalaryRangeFrom" class="form-control shadow">
                    <span asp-validation-for="SalaryRangeFrom" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SalaryRangeTo"></label>
                    <input asp-for="SalaryRangeTo" class="form-control shadow">
                    <span asp-validation-for="SalaryRangeTo" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="required"></label>
                    <textarea asp-for="Description" class="form-control shadow" rows="6"></textarea>
                    <span asp-validation-for="Description" class="small text-danger"></span>
                </div>
                <input type="submit" class="btn btn-outline-primary shadow mt-2 mb-2" value="Save" />
            </form>
        </div>
    </div>
</div>