src/BoostUp/Models/Users/FriendshipInputModel.cs
namespace BoostUp.Models.Users
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    public class FriendshipInputModel
    {
        public string FromId { get; set; }

        [Required]
        public string ToId { get; set; }
    }
}

src/BoostUp/Models/Users/UsersQueryModel.cs
namespace BoostUp.Models.Users
{
    using BoostUp.Services.Users.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    public class UsersQueryModel
    {
        public const int usersPerPage = 12;

        public int CurrentPage { get; init; } = 1;

        public int CompanyId { get; set; }

        public int TotalUsers { get; set; }

        [Display(Name = "Search by name")]
        public string SearchTerm { get; init; }

        public IEnumerable<UsersServiceModel> Users { get; set; } 
    }
}

src/BoostUp/Controllers/FriendshipsController.cs
namespace BoostUp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using BoostUp.Services.Friendships;
    using BoostUp.Infrastructure.Extensions;

    public class FriendshipsController : Controller
    {
        private readonly IFriendshipService friendships;

        public FriendshipsController(IFriendshipService friendships)
        {
            this.friendships = friendships;
        }

        [Authorize]
        public IActionResult Add(string profileUserId)
        {
            var currentUserId = this.User.GetId();

            this.friendships.AddFriendship(currentUserId, profileUserId);

            return RedirectToAction("Profile", "Users", new { id = profileUserId });
        }
    }
}

src/BoostUp/Controllers/UsersController.cs
namespace BoostUp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using BoostUp.Models.Users;
    using BoostUp.Services.Users;
    using BoostUp.Services.Friendships;
    using BoostUp.Infrastructure.Extensions;

    public class UsersController : Controller
    {
        private readonly IUserService users;
        private readonly IFriendshipService friendships;

        public UsersController(IUserService users, IFriendshipService friendships)
        {
            this.users = users;
            this.friendships = friendships;
        }

        [Authorize]
        public IActionResult Profile(string id)
        {
            var user = this.users.Details(id);

            if (user == null)
            {
                return Unauthorized();
            }

            user.CurrentLoggedUser = User.GetId();

            user.FriendShip = this.friendships.GetFriendship(user.CurrentLoggedUser, id);

            return View(user);
        }

        [Authorize]
        public IActionResult All([FromQuery] UsersQueryModel query)
        {
            var userId = User.GetId();

            var usersQuery = this.users.All(
                query.SearchTerm,
                query.CurrentPage,
                UsersQueryModel.usersPerPage,
                query.CompanyId,
                userId);    

            query.Users = usersQuery.Users;
            query.TotalUsers = usersQuery.TotalUsers;

            return View(query);
        }
    }
}

src/BoostUp/Views/Users/All.cshtml
@model UsersQueryModel

@{
    ViewBag.Title = "Users";
}

<!-- Search -->
<form method="get">
    <div class="row mb-2 mt-4">
        <div class="form-group offset-4 col-4">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control shadow" type="text" placeholder="Search" aria-label="Search">
        </div>
    </div>
    <div class="d-flex justify-content-center mb-4">
        <button class="btn btn-outline-primary btn-rounded btn-md shadow" type="submit">
            Search
        </button>
    </div>
</form>

<hr />

<!-- Body -->
@if (!Model.Users.Any())
{
    <h2 class="text-center mt-4"> &#x1F62D;</h2>
    <h3 class="text-center mb-5">No users found!</h3>
}
else
{
    if (Model.CompanyId > 0 && Model.CurrentPage == 1)
    {
        <h3 class="text-center mt-3 mb-5">@Model.TotalUsers @(Model.TotalUsers == 1 ? "employee" : "employees") found for @Model.Users.Select(u => u.CompanyName).FirstOrDefault()</h3>
    }

    <!-- Pagination -->
    <partial name="_UsersPaginationPartial" model="@Model" />

    <div class="row">
        @foreach (var user in Model.Users)
        {
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="card bg-light mb-4 shadow" style="max-width: 18rem;">
                    <div class="card-header">
                        <div>
                            <a asp-action="Profile" asp-controller="Users" asp-route-id="@user.Id">
                                <img class="card-img-top rounded-circle mb-2 img-thumbnail shadow" src="@user.ProfileImagePath" alt="@user.FullName - Profile Picture">
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center mb-0"><b>@user.FullName</b></h5>
                        <p class="card-text text-center mb-1">@user.City, @user.Country</p>
                        @if (user.CompanyName != null)
                        {
                            <p class="card-text text-center">@user.CompanyName</p>
                        }
                        <div class="text-center"><a asp-action="Profile" asp-controller="Users" asp-route-id="@user.Id" class="btn btn-outline-primary shadow">View profile</a></div>
                    </div>
                </div>
            </div>
        }
    </div>

    <!-- Pagination -->
    <partial name="_UsersPaginationPartial" model="@Model" />
}

<hr />

src/BoostUp/Views/Users/Profile.cshtml
@model ProfileServiceModel

@{ ViewBag.Title = "Profile"; }

<link href="~/css/profileView.css" rel="stylesheet" />

<div class="row py-4">
    <div class="col-xl-10 col-md-10 col-sm-12 mx-auto">
        <!-- Profile widget -->
        <div class="bg-white shadow rounded overflow-hidden">
            <div class="px-4 pt-0 pb-4 bg-secondary">
                <div class="media align-items-end profile-header">
                    <div class="profile mr-3">
                        <img src="@Model.ProfileImagePath" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                        @if (Model.CurrentLoggedUser == Model.UserId)
                        {
                               <a asp-area="Identity" asp-page="/Account/Manage/Index" class="btn btn-dark btn-sm btn-block">Edit</a> 
                        }
                        else
                        {
                            if (Model.FriendShip != null)
                            {
                                if (!Model.FriendShip.IsAccepted && Model.FriendShip.ResponderId == Model.CurrentLoggedUser)
                                {
                                     <a class="btn btn-primary btn-sm btn-block" asp-controller="Friendships" asp-action="Accept" asp-route-profileUserId="@Model.UserId">Accept the request</a> 
                                }
                                else if (Model.FriendShip.IsAccepted)
                                {
                                <a class="btn btn-info btn-sm btn-block" asp-controller="Friendships" asp-action="Remove" asp-route-profileUserId="@Model.UserId">Remove from friends</a> 
                                }
                            }
                            else
                            {
                            <a class="btn btn-success btn-sm btn-block" asp-controller="Friendships" asp-action="Add" asp-route-profileUserId="@Model.UserId">Add to friends</a>
                            }
                        }
                    </div>
                    <div class="media-body mb-5 text-white">
                        <h4 class="mt-0 mb-0">@Model.FullName</h4>
                        <p class="small mb-2">@Model.City, @Model.Country</p>
                        @if (Model.JobTitle != null)
                        {
                            <p class="small mt-0 mb-0"><b>Job:</b> @Model.JobTitle</p>
                            }
                        @if (Model.CompanyName != null)
                        {
                            <p class="small"><b>Company:</b> @Model.CompanyName</p>
                          }
                    </div>
                </div>
            </div>
            <div class="bg-light p-4 d-flex justify-content-end text-center">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block">@Model.Friends</h5><small class="text-muted"> <i class="fa fa-user-circle-o mr-1"></i>Connections</small>
                    </li>
                </ul>
            </div>

            <!-- Profile body -->
            <div class="card-body">
                <div id="accordion">
                    <div class="card mb-4">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    <h5><b>About</b></h5>
                                </button>
                            </h5>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="card-body">
                                @if (Model.About != null)
                                {
                    @Model.About}
                            </div>
                        </div>
                    </div>
                </div>
                <div id="accordion">
                    <div class="card mb-4">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    <h5><b>Experience</b></h5>
                                </button>
                            </h5>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="card-body">
                                @if (Model.Experience != null)
                                {
                    @Model.Experience}
                            </div>
                        </div>
                    </div>
                </div>

                <div id="accordion">
                    <div class="card mb-4">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    <h5><b>Education</b></h5>
                                </button>
                            </h5>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="card-body">
                                @if (Model.Education != null)
                                {
                    @Model.Education}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- End profile widget -->
        </div>
    </div>
</div>

src/BoostUp/Views/Users/_UsersPaginationPartial.cshtml
@model UsersQueryModel

@{
    var previousPage = Model.CurrentPage - 1;
    var currentPage = Model.CurrentPage;

    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var lastPage = (int)Math.Ceiling((double)Model.TotalUsers / UsersQueryModel.usersPerPage);
}

<nav>
    <ul class="pagination justify-content-center mb-4">
        <li class="page-item @(currentPage <= 1 ? "disabled" : String.Empty)">
            <a class="page-link"
               asp-controller="Users" asp-action="All"
               asp-route-currentPage="@previousPage"
               asp-route-searchTerm="@Model.SearchTerm"
               asp-route-companyId="@Model.CompanyId">Previous</a>
        </li>
        @for (int i = currentPage - 3; i < currentPage; i++)
        {
            if (i > 0)
            {
                <li class="page-item">
                    <a class="page-link"
                       asp-controller="Users" asp-action="All"
                       asp-route-currentPage="@i"
                       asp-route-searchTerm="@Model.SearchTerm"
                       asp-route-companyId="@Model.CompanyId">@i</a>
                </li>
            }
        }
        <li class="page-item active">
            <span class="page-link">
                @currentPage
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = currentPage + 1; i < currentPage + 4; i++)
        {
            if (i <= lastPage)
            {
                <li class="page-item">
                    <a class="page-link"
                       asp-controller="Users" asp-action="All"
                       asp-route-currentPage="@i"
                       asp-route-searchTerm="@Model.SearchTerm"
                       asp-route-companyId="@Model.CompanyId">@i</a>
                </li>
            }
        }
        <li class="page-item @(currentPage >= lastPage ? "disabled" : String.Empty)">
            <a class="page-link"
               asp-controller="Users" asp-action="All"
               asp-route-currentPage="@(currentPage + 1)"
               asp-route-searchTerm="@Model.SearchTerm"
               asp-route-companyId="@Model.CompanyId">Next</a>
        </li>
    </ul>
</nav>